// Generated by CoffeeScript 1.7.1
(function() {
  var mode;

  mode = process.env.NODE_ENV || "production";

  module.exports = require("" + __dirname + "/../config/" + mode + ".json");

}).call(this);
